apiVersion: v1
kind: Service
metadata:
  name: huddle-landing-page-with-single-introductory-section
  namespace: default
spec:
  selector:
    app: huddle-landing-page-with-single-introductory-section-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
